### PR TITLE
Initial commit. OME.ZARR runnable project

### PR DESCRIPTION
**Pull request by KateMoreva**

### CODE REVIEW

**Comment by tischi** [comment]
Thanks! 

We should try to remove all the stuff that is only needed for N5 (and make an extra repository for this). 

Do you want to remove the N5 specific classes now or later after? I could merge now.

**Comment by KateMoreva** [comment]
> Thanks!
> 
> We should try to remove all the stuff that is only needed for N5 (and make an extra repository for this).
> 
> Do you want to remove the N5 specific classes now or later after? I could merge now.

I am working on removing N5 specific :) 
Could you please wait a bit, if there is something like 15-20 min?

**Comment by tischi** [comment]
Sure! I can also wait longer :)
Just let me know.

**Comment by tischi** [comment]
I made another repo for the n5 stuff: https://github.com/mobie/bigdataviewer-n5/settings/access
But this is **not** high priority, we can populate it another time.

**Comment by KateMoreva** [comment]
> Sure! I can also wait longer :)
> Just let me know.

I cleaned up a bit. There are no unused classes now. But still, there are lots of unused methods and naming dependencies.

**Comment by KateMoreva** [comment]
> I made another repo for the n5 stuff: https://github.com/mobie/bigdataviewer-n5
> But this is **not** high priority, we can populate it another time.

For that, I think we should change the code so that we could use the upstream saalfeldlab version (https://github.com/saalfeldlab/n5-zarr/tree/master/src/main/java/org/janelia/saalfeldlab/n5/zarr)

**Comment by tischi** [comment]
> I cleaned up a bit. There are no unused classes now. But still, there are lots of unused methods and naming dependencies.

Should we merge anyway?

**Comment by KateMoreva** [comment]
> Should we merge anyway?

Well, it depends on how isolated and clean the code should be for the conference.

**Comment by tischi** [comment]
We can clean it up further after having it on master :)
I'll just merge and then look at it.

**Pull request merged**
